find_package(ament_cmake QUIET REQUIRED)
find_package(muparser QUIET)

if(muparser_FOUND)
    message(STATUS "Using system MuParser")
else()
    if(DEFINED fibril_ros_utils_DIR)
        list(APPEND CMAKE_MODULE_PATH "${fibril_ros_utils_DIR}/Modules")
    else()
        list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/Modules")
    endif()

    find_package(muparser QUIET)

    if(muparser_FOUND)
        message(STATUS "Using bundled MuParser")
    else()
        message(FATAL_ERROR "MuParser not found. Please install it or set the path to it.")
    endif()
endif()